### ISSUE TITLE
Screenshots need to be updated/ adding note on previewing html 

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/html-css-learn-workflow-ide#1]
Again since I dont know how to add myself as a student, couldn't update the screenshot for submitting the lab. That screenshot shows the light for local tests passing. 

Also this might be a place to add the note @jmburges raised in an issue on how to preview html. I bolded a placeholder note for it in this lesson. 

cc @matbalez @pletcher

**Comment by pletcher** [comment]
Why is it bad for the screenshot to show that light? There are local tests for some of these labs (such as the first one -- to get them used to the flow).

**Comment by pletcher** [comment]
Such as the first one -- to get them used to the flow.

**Comment by AnnJohn** [comment]
Updated screenshots. First lab shouldn't have tests. 

The other issue of whether to add the note here for previewing HTML is still unresolved.
